/* Generated by Yosys 0.20+70 (git sha1 6e907acf8, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* glift =  1  *)
(* src = "src/MUX.v:3.1-12.10" *)
module MUX(A, B, S, O, A_t, S_t, O_t, B_t);
  (* src = "src/MUX.v:10.12-10.17" *)
  wire _00_;
  wire _01_;
  (* src = "src/MUX.v:10.20-10.26" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "src/MUX.v:10.24-10.26" *)
  wire _22_;
  wire _23_;
  (* src = "src/MUX.v:4.9-4.10" *)
  input A;
  wire A;
  input A_t;
  wire A_t;
  (* src = "src/MUX.v:5.9-5.10" *)
  input B;
  wire B;
  input B_t;
  wire B_t;
  (* src = "src/MUX.v:7.10-7.11" *)
  output O;
  wire O;
  output O_t;
  wire O_t;
  (* src = "src/MUX.v:6.9-6.10" *)
  input S;
  wire S;
  input S_t;
  wire S_t;
  assign _22_ = ~(* src = "src/MUX.v:10.24-10.26" *) S;
  assign _00_ = A &(* src = "src/MUX.v:10.12-10.17" *)  S;
  assign _04_ = ! (* src = "src/MUX.v:10.12-10.17" *) A;
  assign _05_ = ! (* src = "src/MUX.v:10.12-10.17" *) S;
  assign _13_ = A & (* src = "src/MUX.v:10.12-10.17" *) S_t;
  assign _14_ = S & (* src = "src/MUX.v:10.12-10.17" *) A_t;
  assign _15_ = A_t & (* src = "src/MUX.v:10.12-10.17" *) S_t;
  assign _20_ = _13_ | (* src = "src/MUX.v:10.12-10.17" *) _14_;
  assign _01_ = _20_ | (* src = "src/MUX.v:10.12-10.17" *) _15_;
  assign _02_ = B &(* src = "src/MUX.v:10.20-10.26" *)  _22_;
  assign _06_ = ! (* src = "src/MUX.v:10.20-10.26" *) B;
  assign _07_ = ! (* src = "src/MUX.v:10.20-10.26" *) _22_;
  assign _16_ = B & (* src = "src/MUX.v:10.20-10.26" *) _23_;
  assign _17_ = _22_ & (* src = "src/MUX.v:10.20-10.26" *) B_t;
  assign _18_ = B_t & (* src = "src/MUX.v:10.20-10.26" *) _23_;
  assign _21_ = _16_ | (* src = "src/MUX.v:10.20-10.26" *) _17_;
  assign _03_ = _21_ | (* src = "src/MUX.v:10.20-10.26" *) _18_;
  assign O = _00_ |(* src = "src/MUX.v:10.12-10.26" *)  _02_;
  assign _08_ = ! (* src = "src/MUX.v:10.12-10.26" *) _00_;
  assign _09_ = ! (* src = "src/MUX.v:10.12-10.26" *) _02_;
  assign _10_ = _08_ & (* src = "src/MUX.v:10.12-10.26" *) _03_;
  assign _11_ = _09_ & (* src = "src/MUX.v:10.12-10.26" *) _01_;
  assign _12_ = _01_ & (* src = "src/MUX.v:10.12-10.26" *) _03_;
  assign _19_ = _10_ | (* src = "src/MUX.v:10.12-10.26" *) _11_;
  assign O_t = _19_ | (* src = "src/MUX.v:10.12-10.26" *) _12_;
  assign _23_ = S_t;
endmodule
